#!/usr/bin/env python3
"""
Script to translate Dutch Bible quiz questions to English.
This script reads the Dutch questions file and creates an English version.
"""

import json
import re

def translate_question(question_data):
    """Translate a single question from Dutch to English."""
    
    # Translation mappings for common terms
    translations = {
        # Common question words
        "Hoeveel": "How many",
        "Hoe": "How",
        "Wat": "What",
        "Wie": "Who",
        "Waar": "Where",
        "Wanneer": "When",
        "Welke": "Which",
        "Waarom": "Why",
        
        # Common Bible terms
        "Bijbel": "Bible",
        "Bijbelboeken": "Bible books",
        "Nieuwe Testament": "New Testament",
        "Oude Testament": "Old Testament",
        "Jezus": "Jesus",
        "Christus": "Christ",
        "God": "God",
        "Heere": "Lord",
        "Heer": "Lord",
        "Heilige Geest": "Holy Spirit",
        "Heilige": "Holy",
        "Geest": "Spirit",
        "apostel": "apostle",
        "apostelen": "apostles",
        "discipel": "disciple",
        "discipelen": "disciples",
        "profet": "prophet",
        "profeten": "prophets",
        "koning": "king",
        "koningen": "kings",
        "priester": "priest",
        "priesters": "priests",
        "engel": "angel",
        "engelen": "angels",
        
        # Common names
        "Petrus": "Peter",
        "Paulus": "Paul",
        "Johannes": "John",
        "Matteüs": "Matthew",
        "Marcus": "Mark",
        "Lukas": "Luke",
        "Mozes": "Moses",
        "Abraham": "Abraham",
        "David": "David",
        "Salomo": "Solomon",
        "Saul": "Saul",
        "Samuël": "Samuel",
        "Jeremia": "Jeremiah",
        "Jesaja": "Isaiah",
        "Ezechiël": "Ezekiel",
        "Hoséa": "Hosea",
        "Daniël": "Daniel",
        "Jozef": "Joseph",
        "Maria": "Mary",
        "Hanna": "Hannah",
        "Simson": "Samson",
        "Gideon": "Gideon",
        "Herodes": "Herod",
        "Pilatus": "Pilate",
        "Quirinius": "Quirinius",
        "Noach": "Noah",
        "Adam": "Adam",
        "Eva": "Eve",
        
        # Places
        "Bethlehem": "Bethlehem",
        "Jeruzalem": "Jerusalem",
        "Galilea": "Galilee",
        "Nazareth": "Nazareth",
        "Egypte": "Egypt",
        "Israël": "Israel",
        "Kanaän": "Canaan",
        "Sinaï": "Sinai",
        "Horeb": "Horeb",
        "Eden": "Eden",
        "Paradijs": "Paradise",
        "hemel": "heaven",
        "hel": "hell",
        "aarde": "earth",
        "zee": "sea",
        "rivier": "river",
        "berg": "mountain",
        "woestijn": "desert",
        "tuin": "garden",
        "tempel": "temple",
        "synagoge": "synagogue",
        "kerk": "church",
        "huis": "house",
        "stad": "city",
        "land": "land",
        
        # Common actions and concepts
        "genas": "healed",
        "genazen": "healed",
        "verloste": "redeemed",
        "verloste": "redeemed",
        "stierf": "died",
        "sterven": "die",
        "opstond": "rose",
        "opstanding": "resurrection",
        "geboren": "born",
        "geboren": "born",
        "geboorte": "birth",
        "leven": "life",
        "dood": "death",
        "liefde": "love",
        "geloof": "faith",
        "hoop": "hope",
        "vrede": "peace",
        "vreugde": "joy",
        "verdriet": "sorrow",
        "angst": "fear",
        "vrede": "peace",
        "gerechtigheid": "righteousness",
        "genade": "grace",
        "barmhartigheid": "mercy",
        "vergeving": "forgiveness",
        "verlossing": "salvation",
        "zegen": "blessing",
        "vloek": "curse",
        "zonde": "sin",
        "zondig": "sinful",
        "heilig": "holy",
        "rein": "pure",
        "onrein": "unclean",
        "goed": "good",
        "kwaad": "evil",
        "waarheid": "truth",
        "leugen": "lie",
        "licht": "light",
        "duisternis": "darkness",
        "dag": "day",
        "nacht": "night",
        "morgen": "morning",
        "avond": "evening",
        "jaar": "year",
        "maand": "month",
        "week": "week",
        "dag": "day",
        "uur": "hour",
        "minuut": "minute",
        "seconde": "second",
        
        # Common adjectives
        "groot": "great",
        "klein": "small",
        "lang": "long",
        "kort": "short",
        "hoog": "high",
        "laag": "low",
        "breed": "wide",
        "smal": "narrow",
        "dik": "thick",
        "dun": "thin",
        "zwaar": "heavy",
        "licht": "light",
        "sterk": "strong",
        "zwak": "weak",
        "rijk": "rich",
        "arm": "poor",
        "jong": "young",
        "oud": "old",
        "nieuw": "new",
        "oud": "old",
        "mooi": "beautiful",
        "lelijk": "ugly",
        "goed": "good",
        "slecht": "bad",
        "waar": "true",
        "vals": "false",
        "echt": "real",
        "nep": "fake",
        
        # Common verbs
        "zijn": "be",
        "hebben": "have",
        "doen": "do",
        "gaan": "go",
        "komen": "come",
        "zien": "see",
        "horen": "hear",
        "zeggen": "say",
        "spreken": "speak",
        "luisteren": "listen",
        "kijken": "look",
        "zoeken": "search",
        "vinden": "find",
        "geven": "give",
        "nemen": "take",
        "maken": "make",
        "bouwen": "build",
        "werken": "work",
        "spelen": "play",
        "leren": "learn",
        "onderwijzen": "teach",
        "helpen": "help",
        "redden": "save",
        "verloren": "lost",
        "gevonden": "found",
        "winnen": "win",
        "verliezen": "lose",
        "strijden": "fight",
        "vechten": "fight",
        "doden": "kill",
        "sterven": "die",
        "leven": "live",
        "wonen": "live",
        "slapen": "sleep",
        "wakker": "awake",
        "eten": "eat",
        "drinken": "drink",
        "lopen": "walk",
        "rennen": "run",
        "zitten": "sit",
        "staan": "stand",
        "liggen": "lie",
        "zwaaien": "wave",
        "knielen": "kneel",
        "bidden": "pray",
        "aanbidden": "worship",
        "dienen": "serve",
        "volgen": "follow",
        "leiden": "lead",
        "regeren": "rule",
        "koning": "king",
        "koningin": "queen",
        "prins": "prince",
        "prinses": "princess",
        
        # Common nouns
        "man": "man",
        "vrouw": "woman",
        "kind": "child",
        "kinderen": "children",
        "baby": "baby",
        "jongen": "boy",
        "meisje": "girl",
        "vader": "father",
        "moeder": "mother",
        "zoon": "son",
        "dochter": "daughter",
        "broer": "brother",
        "zus": "sister",
        "familie": "family",
        "vriend": "friend",
        "vrienden": "friends",
        "vijand": "enemy",
        "vijanden": "enemies",
        "volk": "people",
        "natie": "nation",
        "land": "country",
        "stad": "city",
        "dorp": "village",
        "huis": "house",
        "deur": "door",
        "raam": "window",
        "tafel": "table",
        "stoel": "chair",
        "bed": "bed",
        "kamer": "room",
        "keuken": "kitchen",
        "slaapkamer": "bedroom",
        "badkamer": "bathroom",
        "tuin": "garden",
        "boom": "tree",
        "bloem": "flower",
        "gras": "grass",
        "water": "water",
        "vuur": "fire",
        "lucht": "air",
        "aarde": "earth",
        "steen": "stone",
        "hout": "wood",
        "ijzer": "iron",
        "goud": "gold",
        "zilver": "silver",
        "koper": "copper",
        "brood": "bread",
        "vlees": "meat",
        "vis": "fish",
        "fruit": "fruit",
        "groente": "vegetable",
        "melk": "milk",
        "wijn": "wine",
        "bier": "beer",
        "koffie": "coffee",
        "thee": "tea",
        "suiker": "sugar",
        "zout": "salt",
        "peper": "pepper",
        "olie": "oil",
        "boter": "butter",
        "kaas": "cheese",
        "ei": "egg",
        "honing": "honey",
        "appel": "apple",
        "peer": "pear",
        "banaan": "banana",
        "druif": "grape",
        "sinaasappel": "orange",
        "citroen": "lemon",
        "aardbei": "strawberry",
        "kers": "cherry",
        "perzik": "peach",
        "pruim": "plum",
        "dadel": "date",
        "vijg": "fig",
        "granaatappel": "pomegranate",
        "olijf": "olive",
        "noot": "nut",
        "amandel": "almond",
        "walnoot": "walnut",
        "hazelnoot": "hazelnut",
        "pistache": "pistachio",
        "kastanje": "chestnut",
        "kokosnoot": "coconut",
        "ananas": "pineapple",
        "mango": "mango",
        "papaja": "papaya",
        "kiwi": "kiwi",
        "avocado": "avocado",
        "tomaat": "tomato",
        "komkommer": "cucumber",
        "wortel": "carrot",
        "ui": "onion",
        "knoflook": "garlic",
        "aardappel": "potato",
        "rijst": "rice",
        "tarwe": "wheat",
        "gerst": "barley",
        "haver": "oats",
        "rogge": "rye",
        "maïs": "corn",
        "bonen": "beans",
        "erwten": "peas",
        "linzen": "lentils",
        "kikkererwten": "chickpeas",
        "sojabonen": "soybeans",
        "pinda": "peanut",
        "zonnebloem": "sunflower",
        "saffraan": "saffron",
        "kaneel": "cinnamon",
        "nootmuskaat": "nutmeg",
        "kruidnagel": "clove",
        "gember": "ginger",
        "kurkuma": "turmeric",
        "paprika": "paprika",
        "chili": "chili",
        "mosterd": "mustard",
        "munt": "mint",
        "basilicum": "basil",
        "oregano": "oregano",
        "tijm": "thyme",
        "rozemarijn": "rosemary",
        "salie": "sage",
        "peterselie": "parsley",
        "koriander": "coriander",
        "dille": "dill",
        "laurier": "bay leaf",
        "kervel": "chervil",
        "borage": "borage",
        "citroenmelisse": "lemon balm",
        "lavendel": "lavender",
        "kamille": "chamomile",
        "echinacea": "echinacea",
        "ginseng": "ginseng",
        "ginkgo": "ginkgo",
        "valeriaan": "valerian",
        "passiebloem": "passionflower",
        "sint-janskruid": "St. John's wort",
        "goudsbloem": "marigold",
        "nagelkruid": "clove",
        "anijs": "anise",
        "venkel": "fennel",
        "karwij": "caraway",
        "komijn": "cumin",
        "kardemom": "cardamom",
        "vanille": "vanilla",
        "cacao": "cocoa",
        "koffie": "coffee",
        "thee": "tea",
        "kruidenthee": "herbal tea",
        "rooibos": "rooibos",
        "maté": "mate",
        "ginseng": "ginseng",
        "jasmijn": "jasmine",
        "roos": "rose",
        "lavendel": "lavender",
        "mint": "mint",
        "pepermunt": "peppermint",
        "spearmint": "spearmint",
        "chocolade": "chocolate",
        "candy": "candy",
        "snoep": "candy",
        "koek": "cookie",
        "cake": "cake",
        "taart": "pie",
        "pudding": "pudding",
        "ijs": "ice cream",
        "sorbet": "sorbet",
        "yoghurt": "yogurt",
        "kwark": "quark",
        "room": "cream",
        "slagroom": "whipped cream",
        "custard": "custard",
        "flan": "flan",
        "crème brûlée": "crème brûlée",
        "tiramisu": "tiramisu",
        "cheesecake": "cheesecake",
        "brownie": "brownie",
        "muffin": "muffin",
        "pancake": "pancake",
        "wafel": "waffle",
        "french toast": "french toast",
        "croissant": "croissant",
        "bagel": "bagel",
        "donut": "donut",
        "pretzel": "pretzel",
        "cracker": "cracker",
        "biscuit": "biscuit",
        "scone": "scone",
        "muffin": "muffin",
        "cupcake": "cupcake",
        "macaron": "macaron",
        "eclair": "éclair",
        "profiterole": "profiterole",
        "cannoli": "cannoli",
        "baklava": "baklava",
        "strudel": "strudel",
        "pavlova": "pavlova",
        "trifle": "trifle",
        "tiramisu": "tiramisu",
        "gelato": "gelato",
        "sorbet": "sorbet",
        "granita": "granita",
        "sherbet": "sherbet",
        "frozen yogurt": "frozen yogurt",
        "frozen custard": "frozen custard",
        "soft serve": "soft serve",
        "slushie": "slushie",
        "smoothie": "smoothie",
        "milkshake": "milkshake",
        "frappé": "frappé",
        "cappuccino": "cappuccino",
        "latte": "latte",
        "espresso": "espresso",
        "americano": "americano",
        "macchiato": "macchiato",
        "mocha": "mocha",
        "frappuccino": "frappuccino",
        "cold brew": "cold brew",
        "nitro coffee": "nitro coffee",
        "bulletproof coffee": "bulletproof coffee",
        "dalgona coffee": "dalgona coffee",
        "matcha": "matcha",
        "green tea": "green tea",
        "black tea": "black tea",
        "white tea": "white tea",
        "oolong tea": "oolong tea",
        "pu-erh tea": "pu-erh tea",
        "chai": "chai",
        "masala chai": "masala chai",
        "bubble tea": "bubble tea",
        "boba": "boba",
        "tapioca": "tapioca",
        "jelly": "jelly",
        "pudding": "pudding",
        "custard": "custard",
        "flan": "flan",
        "panna cotta": "panna cotta",
        "mousse": "mousse",
        "soufflé": "soufflé",
        "parfait": "parfait",
        "trifle": "trifle",
        "tiramisu": "tiramisu",
        "cheesecake": "cheesecake",
        "brownie": "brownie",
        "blondie": "blondie",
        "fudge": "fudge",
        "toffee": "toffee",
        "caramel": "caramel",
        "butterscotch": "butterscotch",
        "nougat": "nougat",
        "marzipan": "marzipan",
        "fondant": "fondant",
        "ganache": "ganache",
        "frosting": "frosting",
        "icing": "icing",
        "glaze": "glaze",
        "syrup": "syrup",
        "honey": "honey",
        "molasses": "molasses",
        "agave": "agave",
        "maple syrup": "maple syrup",
        "corn syrup": "corn syrup",
        "golden syrup": "golden syrup",
        "treacle": "treacle",
        "jam": "jam",
        "jelly": "jelly",
        "marmalade": "marmalade",
        "preserves": "preserves",
        "compote": "compote",
        "chutney": "chutney",
        "relish": "relish",
        "pickle": "pickle",
        "pickled": "pickled",
        "fermented": "fermented",
        "cured": "cured",
        "smoked": "smoked",
        "dried": "dried",
        "dehydrated": "dehydrated",
        "freeze-dried": "freeze-dried",
        "canned": "canned",
        "jarred": "jarred",
        "bottled": "bottled",
        "packaged": "packaged",
        "fresh": "fresh",
        "frozen": "frozen",
        "raw": "raw",
        "cooked": "cooked",
        "baked": "baked",
        "roasted": "roasted",
        "grilled": "grilled",
        "fried": "fried",
        "sautéed": "sautéed",
        "steamed": "steamed",
        "boiled": "boiled",
        "poached": "poached",
        "braised": "braised",
        "stewed": "stewed",
        "simmered": "simmered",
        "blanched": "blanched",
        "parboiled": "parboiled",
        "al dente": "al dente",
        "tender": "tender",
        "crispy": "crispy",
        "crunchy": "crunchy",
        "chewy": "chewy",
        "soft": "soft",
        "firm": "firm",
        "hard": "hard",
        "smooth": "smooth",
        "rough": "rough",
        "coarse": "coarse",
        "fine": "fine",
        "thick": "thick",
        "thin": "thin",
        "dense": "dense",
        "light": "light",
        "fluffy": "fluffy",
        "airy": "airy",
        "creamy": "creamy",
        "rich": "rich",
        "heavy": "heavy",
        "light": "light",
        "mild": "mild",
        "spicy": "spicy",
        "hot": "hot",
        "cold": "cold",
        "warm": "warm",
        "cool": "cool",
        "sweet": "sweet",
        "sour": "sour",
        "bitter": "bitter",
        "salty": "salty",
        "savory": "savory",
        "umami": "umami",
        "tangy": "tangy",
        "tart": "tart",
        "sharp": "sharp",
        "mellow": "mellow",
        "bland": "bland",
        "flavorful": "flavorful",
        "tasteless": "tasteless",
        "delicious": "delicious",
        "tasty": "tasty",
        "yummy": "yummy",
        "scrumptious": "scrumptious",
        "delectable": "delectable",
        "appetizing": "appetizing",
        "mouthwatering": "mouthwatering",
        "divine": "divine",
        "heavenly": "heavenly",
        "outstanding": "outstanding",
        "excellent": "excellent",
        "superb": "superb",
        "magnificent": "magnificent",
        "wonderful": "wonderful",
        "amazing": "amazing",
        "incredible": "incredible",
        "fantastic": "fantastic",
        "fabulous": "fabulous",
        "marvelous": "marvelous",
        "splendid": "splendid",
        "gorgeous": "gorgeous",
        "beautiful": "beautiful",
        "lovely": "lovely",
        "charming": "charming",
        "delightful": "delightful",
        "pleasant": "pleasant",
        "nice": "nice",
        "good": "good",
        "great": "great",
        "awesome": "awesome",
        "cool": "cool",
        "neat": "neat",
        "wow": "wow",
        "wonderful": "wonderful",
        "amazing": "amazing",
        "incredible": "incredible",
        "fantastic": "fantastic",
        "fabulous": "fabulous",
        "marvelous": "marvelous",
        "splendid": "splendid",
        "gorgeous": "gorgeous",
        "beautiful": "beautiful",
        "lovely": "lovely",
        "charming": "charming",
        "delightful": "delightful",
        "pleasant": "pleasant",
        "nice": "nice",
        "good": "good",
        "great": "great",
        "awesome": "awesome",
        "cool": "cool",
        "neat": "neat",
        "wow": "wow",
    }
    
    # Translate the question
    question = question_data.get('vraag', '')
    translated_question = translate_text(question, translations)
    
    # Translate the correct answer
    correct_answer = question_data.get('juisteAntwoord', '')
    translated_correct = translate_text(correct_answer, translations)
    
    # Translate the wrong answers
    wrong_answers = question_data.get('fouteAntwoorden', [])
    translated_wrong = [translate_text(answer, translations) for answer in wrong_answers]
    
    # Translate biblical reference
    biblical_ref = question_data.get('biblicalReference', '')
    translated_ref = translate_biblical_reference(biblical_ref) if biblical_ref else None
    
    # Translate categories
    categories = question_data.get('categories', [])
    translated_categories = [translate_text(cat, translations) for cat in categories]
    
    # Create translated question
    translated_question_data = {
        'vraag': translated_question,
        'juisteAntwoord': translated_correct,
        'fouteAntwoorden': translated_wrong,
        'moeilijkheidsgraad': question_data.get('moeilijkheidsgraad', 1),
        'type': question_data.get('type', 'mc'),
        'categories': translated_categories,
        'biblicalReference': translated_ref
    }
    
    return translated_question_data

def translate_text(text, translations):
    """Translate text using the translation dictionary."""
    if not text:
        return text
    
    # Split text into words and translate each word
    words = text.split()
    translated_words = []
    
    for word in words:
        # Remove punctuation for lookup
        clean_word = re.sub(r'[^\w]', '', word.lower())
        
        # Check for exact match
        if clean_word in translations:
            translated_word = translations[clean_word]
            # Preserve original capitalization
            if word.istitle():
                translated_word = translated_word.title()
            elif word.isupper():
                translated_word = translated_word.upper()
            translated_words.append(translated_word)
        else:
            # Try partial matches
            found = False
            for dutch_word, english_word in translations.items():
                if clean_word.startswith(dutch_word) or dutch_word in clean_word:
                    translated_word = english_word
                    if word.istitle():
                        translated_word = translated_word.title()
                    elif word.isupper():
                        translated_word = translated_word.upper()
                    translated_words.append(translated_word)
                    found = True
                    break
            
            if not found:
                translated_words.append(word)
    
    return ' '.join(translated_words)

def translate_biblical_reference(ref):
    """Translate biblical reference from Dutch to English."""
    if not ref:
        return ref
    
    # Common book name translations
    book_translations = {
        'Matthéus': 'Matthew',
        'Marcus': 'Mark',
        'Lukas': 'Luke',
        'Johannes': 'John',
        'Handelingen': 'Acts',
        'Romeinen': 'Romans',
        '1 Korinthe': '1 Corinthians',
        '2 Korinthe': '2 Corinthians',
        'Galaten': 'Galatians',
        'Efeze': 'Ephesians',
        'Filippenzen': 'Philippians',
        'Kolossenzen': 'Colossians',
        '1 Thessalonicenzen': '1 Thessalonians',
        '2 Thessalonicenzen': '2 Thessalonians',
        '1 Timotheüs': '1 Timothy',
        '2 Timotheüs': '2 Timothy',
        'Titus': 'Titus',
        'Filemon': 'Philemon',
        'Hebreeën': 'Hebrews',
        'Jakobus': 'James',
        '1 Petrus': '1 Peter',
        '2 Petrus': '2 Peter',
        '1 Johannes': '1 John',
        '2 Johannes': '2 John',
        '3 Johannes': '3 John',
        'Judas': 'Jude',
        'Openbaring': 'Revelation',
        'Genesis': 'Genesis',
        'Exodus': 'Exodus',
        'Leviticus': 'Leviticus',
        'Numeri': 'Numbers',
        'Deuteronomium': 'Deuteronomy',
        'Jozua': 'Joshua',
        'Richteren': 'Judges',
        'Ruth': 'Ruth',
        '1 Samuël': '1 Samuel',
        '2 Samuël': '2 Samuel',
        '1 Koningen': '1 Kings',
        '2 Koningen': '2 Kings',
        '1 Kronieken': '1 Chronicles',
        '2 Kronieken': '2 Chronicles',
        'Ezra': 'Ezra',
        'Nehemia': 'Nehemiah',
        'Esther': 'Esther',
        'Job': 'Job',
        'Psalmen': 'Psalms',
        'Spreuken': 'Proverbs',
        'Prediker': 'Ecclesiastes',
        'Hooglied': 'Song of Songs',
        'Jesaja': 'Isaiah',
        'Jeremia': 'Jeremiah',
        'Klaagliederen': 'Lamentations',
        'Ezechiël': 'Ezekiel',
        'Daniël': 'Daniel',
        'Hoséa': 'Hosea',
        'Joël': 'Joel',
        'Amos': 'Amos',
        'Obadja': 'Obadiah',
        'Jona': 'Jonah',
        'Micha': 'Micah',
        'Nahum': 'Nahum',
        'Habakuk': 'Habakkuk',
        'Zefanja': 'Zephaniah',
        'Haggaï': 'Haggai',
        'Zacharia': 'Zechariah',
        'Maleachi': 'Malachi',
    }
    
    # Try to translate the book name
    for dutch_book, english_book in book_translations.items():
        if ref.startswith(dutch_book):
            return ref.replace(dutch_book, english_book, 1)
    
    return ref

def main():
    """Main function to translate all questions."""
    print("Loading Dutch questions...")
    
    # Load Dutch questions
    with open('assets/questions-nl-sv.json', 'r', encoding='utf-8') as f:
        dutch_questions = json.load(f)
    
    print(f"Found {len(dutch_questions)} questions to translate")
    
    # Translate questions
    english_questions = []
    for i, question in enumerate(dutch_questions):
        print(f"Translating question {i+1}/{len(dutch_questions)}...")
        translated = translate_question(question)
        english_questions.append(translated)
    
    # Save English questions
    print("Saving English questions...")
    with open('assets/questions-en.json', 'w', encoding='utf-8') as f:
        json.dump(english_questions, f, ensure_ascii=False, indent=2)
    
    print("Translation complete!")

if __name__ == "__main__":
    main()