class ScripturaBookMapper {
  // List of valid book names as defined by the Scriptura API.
  static const List<String> validBooks = [
    'Genesis',
    'Exodus',
    'Leviticus',
    'Numberi',
    'Deuteronomium',
    'Jozua',
    'Richtere',
    'Ruth',
    '1 Samuël',
    '2 Samuël',
    '1 Koningen',
    '2 Koningen',
    '1 Kronieken',
    '2 Kronieken',
    'Ezra',
    'Nehemia',
    'Esther',
    'Job',
    'Psalmen',
    'Spreuken',
    'Prediker',
    'Hooglied',
    'Jesaja',
    'Jeremia',
    'Klaagliederen',
    'Ezechiël',
    'Daniël',
    'Hosea',
    'Joël',
    'Amos',
    'Obadja',
    'Jona',
    'Micha',
    'Nahum',
    'Habakuk',
    'Zefanja',
    'Haggaï',
    'Zacharia',
    'Maleachi',
    'Mattheüs',
    'Markus',
    'Lukas',
    'Johannes',
    'Handelingen',
    'Romeinen',
    '1 Corinthiërs',
    '2 Corinthiër',
    'Galaten',
    'Efeziërs',
    'Filippenzen',
    'Colossenzen',
    '1 Thessalonicenzen',
    '2 Thessalonicenzen',
    '1 Timotheüs',
    '2 Timotheüs',
    'Titus',
    'Filémon',
    'Hebreeën',
    'Jakobus',
    '1 Petrus',
    '2 Petrus',
    '1 Johannes',
    '2 Johannes',
    '3 Johannes',
    'Judas',
    'Openbaring',
  ];

  /// Returns true if the given book name is a valid Scriptura book.
  static bool isValidBook(String bookName) {
    return validBooks.contains(bookName);
  }
}
